export const Estabelecimentos = [
  {
    id: 1,
    nome: "Restaurante São Miguel",
    open: true,
    distancia: 5,
    avaliacao: 3,
    caracteristicas: [
      "Drinks",
      "Carnes",
      "Peixes",
      "Churrasco",
    ],
    image: "https://vejario.abril.com.br/wp-content/uploads/2020/11/emile.jpg",
  },
  {
    id: 2,
    nome: "Restaurante Novo Hostizr",
    open: false,
    distancia: 20,
    avaliacao: 5,
    caracteristicas: [
      "Cortes finos",
      "Drinks",
      "Vegano",
      "Privativo",
    ],
    image: "https://www.granmarquise.com.br/wp-content/uploads/2018/06/lo.jpg",
  },
  {
    id: 3,
    nome: "Bar Quintal Da Mooca",
    open: true,
    distancia: 10,
    avaliacao: 5,
    caracteristicas: [
      "Comida Brasileira",
      "Bar",
      "Mesas ao ar livre",
      "Wi-Fi gratuito",
      "Lugares sentados",
    ],
    image: "https://media-cdn.tripadvisor.com/media/photo-o/19/f8/33/17/uma-delicia.jpg",
  },
  {
    id: 4,
    nome: "Bar do Luiz Fernandes",
    open: false,
    distancia: 12,
    avaliacao: 4,
    caracteristicas: [
      "Serviço de mesa",
      "Bar",
      "Comida de boteco",
      "Bons Drinks",
      "Lugares sentados",
    ],
    image: "https://media-cdn.tripadvisor.com/media/photo-o/0e/4b/53/66/bolinhos-de-carne-e-petiscos.jpg",
  },
  {
    id: 5,
    nome: "Must Bar",
    open: true,
    distancia: 22,
    avaliacao: 3,
    caracteristicas: [
      "Opções vegan",
      "Bar",
      "Hamburgueria",
      "Opções sem glúten",
      "Brunch",
    ],
    image: "https://media-cdn.tripadvisor.com/media/photo-o/10/af/09/99/fraldinha-batata-rustica.jpg",
  },
  {
    id: 6,
    nome: "FrangO",
    open: true,
    distancia: 22,
    avaliacao: 3,
    caracteristicas: [
      "Bebidas",
      "Últimas horas da noite",
      "Hamburgueria",
      "Cerveja e vinho",
      "Comida Brasileira",
    ],
    image: "https://media-cdn.tripadvisor.com/media/photo-o/0f/a8/49/00/salao-de-baixo.jpg",
  },
  {
    id: 7,
    nome: "Paella Rio Sampa",
    open: true,
    distancia: 30,
    avaliacao: 5,
    caracteristicas: [
      "Comida Mediterrânea",
      "Europeu",
      "Bar de vinhos",
      "Cerveja e vinho",
      "Marisco",
    ],
    image: "https://media-cdn.tripadvisor.com/media/photo-m/1280/22/cc/cb/fd/caption.jpg",
  },
  {
    id: 8,
    nome: "Tadashii Japanese Restauran",
    open: true,
    distancia: 4,
    avaliacao: 5,
    caracteristicas: [
      "Japonesa",
      "Sushi",
      "Saudável",
      "Opções sem glúten",
      "Adequado a vegetarianos",
    ],
    image: "https://media-cdn.tripadvisor.com/media/photo-o/12/20/c1/73/prato-principal-festival.jpg",
  },
  {
    id: 9,
    nome: "Fuego Celeste Parrillada",
    open: false,
    distancia: 4,
    avaliacao: 5,
    caracteristicas: [
      "Steakhouse",
      "Latino",
      "Churrasco",
      "Bebidas",
      "Wi-Fi gratuito",
    ],
    image: "https://media-cdn.tripadvisor.com/media/photo-o/12/d1/81/a3/asado-de-tira-black-angus.jpg",
  },
  {
    id: 10,
    nome: "Picanharia dos Amigos - Vila Leopoldina",
    open: true,
    distancia: 14,
    avaliacao: 4,
    caracteristicas: [
      "Steakhouse",
      "Últimas horas da noite",
      "Permite a entrada de cães",
      "Bebidas",
      "Mesas ao ar livre",
    ],
    image: "https://media-cdn.tripadvisor.com/media/photo-m/1280/19/bb/5a/84/picanharia-dos-amigos.jpg",
  },
  {
    id: 11,
    nome: "CipóRestô",
    open: true,
    distancia: 23,
    avaliacao: 5,
    caracteristicas: [
      "Comida Brasileira",
      "Adequado a vegetarianos",
      "Permite a entrada de cães",
      "Bebidas",
      "Mesas ao ar livre",
    ],
    image: "https://media-cdn.tripadvisor.com/media/photo-m/1280/1d/04/e3/b5/ciporesto.jpg",
  },
  {
    id: 12,
    nome: "Adega Santiago",
    open: false,
    distancia: 33,
    avaliacao: 5,
    caracteristicas: [
      "Comida Mediterrânea",
      "Portuguesa",
      "Acessível a cadeiras de rodas",
      "Bebidas",
      "Estacionamento disponível",
    ],
    image: "https://media-cdn.tripadvisor.com/media/photo-w/1a/f6/30/72/caption.jpg",
  },
  {
    id: 13,
    nome: "Banqueta Bar",
    open: true,
    distancia: 28,
    avaliacao: 5,
    caracteristicas: [
      "Bar",
      "Vinho",
      "Bons Drinks",
      "Adequado a vegetarianos",
      "Estacionamento disponível",
    ],
    image: "https://media-cdn.tripadvisor.com/media/photo-m/1280/13/fa/ab/cb/boulevardier-jack-daniel.jpg",
  },
  {
    id: 14,
    nome: "The Blue Pub",
    open: true,
    distancia: 48,
    avaliacao: 3,
    caracteristicas: [
      "Irlandês",
      "Pub",
      "Bons Drinks",
      "Musica ao vivo",
      "Reservas",
    ],
    image: "https://media-cdn.tripadvisor.com/media/photo-m/1280/1d/6b/5c/bb/caption.jpg",
  },
  {
    id: 15,
    nome: "Boteco São Bento",
    open: false,
    distancia: 19,
    avaliacao: 4,
    caracteristicas: [
      "Brasileira",
      "Bar",
      "Bons Drinks",
      "Musica ao vivo",
      "Bebidas",
    ],
    image: "https://media-cdn.tripadvisor.com/media/photo-o/09/f4/8f/34/img-20160105-120658863.jpg",
  },
  {
    id: 16,
    nome: "Boteco São Bento",
    open: false,
    distancia: 19,
    avaliacao: 4,
    caracteristicas: [
      "Sul Americana",
      "Bar",
      "Serviço de mesa",
      "Musica ao vivo",
      "Bebidas alcoólicas",
    ],
    image: "https://media-cdn.tripadvisor.com/media/photo-w/1a/5c/5c/61/photo0jpg.jpg",
  },
  {
    id: 17,
    nome: "Ambar Cervejas Artesanais",
    open: true,
    distancia: 11,
    avaliacao: 5,
    caracteristicas: [
      "Almoço e Jantar",
      "Bar",
      "Vinhos",
      "Ambiente Coberto",
      "Cervejas Artesanais",
    ],
    image: "https://media-cdn.tripadvisor.com/media/photo-o/10/02/7a/59/salao.jpg",
  },
  {
    id: 18,
    nome: "Bar do Juarez - Pinheiros",
    open: true,
    distancia: 8,
    avaliacao: 3,
    caracteristicas: [
      "Grill",
      "Contemporâneo",
      "Vinhos",
      "Reservas",
      "Cervejas Artesanais",
    ],
    image: "https://media-cdn.tripadvisor.com/media/photo-m/1280/19/0d/d4/8e/quarta-sabado-e-domingo.jpg",
  },
  {
    id: 19,
    nome: "Kia Ora",
    open: true,
    distancia: 28,
    avaliacao: 4,
    caracteristicas: [
      "Bar",
      "Pub",
      "Bebidas",
      "Musica ao vivo",
      "Cervejas Artesanais",
    ],
    image: "https://media-cdn.tripadvisor.com/media/photo-w/0e/c9/e4/00/photo1jpg.jpg",
  },
  {
    id: 20,
    nome: "oteco La Gorgona",
    open: false,
    distancia: 11,
    avaliacao: 4,
    caracteristicas: [
      "Colombiana",
      "Comida de rua",
      "Bebidas",
      "Adequado a vegetarianos",
      "Café",
    ],
    image: "https://media-cdn.tripadvisor.com/media/photo-m/1280/1a/db/89/48/comida-tradicional-da.jpg",
  },
];
